# Generated by Django 5.2.15 on 2026-06-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='客户姓名')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('id_number', models.CharField(blank=True, max_length=30, verbose_name='身份证号')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(max_length=50, unique=True, verbose_name='保单号')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='保费')),
                ('insured_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='保额')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underwriting.customer', verbose_name='客户')),
            ],
        ),
        migrations.CreateModel(
            name='UnderwritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('health_notice', models.TextField(blank=True, verbose_name='健康告知')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=20, verbose_name='风险等级')),
                ('status', models.CharField(choices=[('pending', '待核保'), ('reviewing', '审核中'), ('approved', '通过'), ('extra_fee', '加费'), ('excluded', '除外'), ('postponed', '延期'), ('rejected', '拒保'), ('need_material', '补充资料')], default='pending', max_length=30, verbose_name='核保状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underwriting.policy', verbose_name='保单')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=50, verbose_name='核保结论')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underwriting.underwritingtask', verbose_name='核保任务')),
            ],
        ),
    ]
