# Generated by Django 5.2.15 on 2026-06-11 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='agent_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='业务员/渠道人员'),
        ),
        migrations.AddField(
            model_name='policy',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='投保人姓名'),
        ),
        migrations.AddField(
            model_name='policy',
            name='coverage_period',
            field=models.CharField(blank=True, max_length=30, verbose_name='保障期间'),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='生效日期'),
        ),
        migrations.AddField(
            model_name='policy',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='终止日期'),
        ),
        migrations.AddField(
            model_name='policy',
            name='insured_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='被保人姓名'),
        ),
        migrations.AddField(
            model_name='policy',
            name='pay_mode',
            field=models.CharField(choices=[('single', '趸交'), ('yearly', '年交'), ('monthly', '月交')], default='yearly', max_length=20, verbose_name='缴费方式'),
        ),
        migrations.AddField(
            model_name='policy',
            name='pay_period',
            field=models.CharField(blank=True, max_length=30, verbose_name='缴费期间'),
        ),
        migrations.AddField(
            model_name='policy',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='产品类型'),
        ),
        migrations.AddField(
            model_name='policy',
            name='proposal_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='投保单号'),
        ),
        migrations.AddField(
            model_name='policy',
            name='relation',
            field=models.CharField(blank=True, max_length=30, verbose_name='投被保人关系'),
        ),
        migrations.AddField(
            model_name='policy',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='policy',
            name='sales_channel',
            field=models.CharField(blank=True, max_length=50, verbose_name='销售渠道'),
        ),
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('underwriting', '核保中'), ('approved', '已承保'), ('rejected', '拒保'), ('cancelled', '已取消')], default='submitted', max_length=30, verbose_name='保单状态'),
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='insured_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='基本保额'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='年缴保费'),
        ),
    ]
