# Generated by Django 5.2.15 on 2026-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0002_policy_agent_name_policy_applicant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('personal', '个人客户'), ('company', '企业客户')], default='personal', max_length=20, verbose_name='客户类型'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='注册地址'),
        ),
        migrations.AddField(
            model_name='customer',
            name='unified_social_credit_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='客户名称'),
        ),
    ]
