# Generated by Django 5.2.15 on 2026-06-12 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0003_customer_company_name_customer_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=50, unique=True, verbose_name='投保申请号')),
                ('insurance_type', models.CharField(choices=[('auto', '车险'), ('property', '财产险'), ('liability', '责任险'), ('engineering', '工程险'), ('cargo', '货运险'), ('other', '其他')], default='property', max_length=30, verbose_name='险种类型')),
                ('subject_name', models.CharField(max_length=100, verbose_name='保险标的')),
                ('subject_address', models.CharField(blank=True, max_length=200, verbose_name='标的地址')),
                ('insured_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='保险金额')),
                ('estimated_premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预估保费')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('underwriting', '核保中'), ('approved', '通过'), ('rejected', '拒保'), ('need_material', '补充资料'), ('cancelled', '已取消')], default='submitted', max_length=30, verbose_name='申请状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underwriting.customer', verbose_name='客户')),
            ],
        ),
    ]
