# Generated by Django 5.2.15 on 2026-06-12 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0004_insuranceapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=20, verbose_name='风险等级')),
                ('risk_score', models.PositiveIntegerField(default=50, verbose_name='风险评分')),
                ('risk_factors', models.TextField(blank=True, verbose_name='风险因素')),
                ('conclusion', models.TextField(blank=True, verbose_name='评估结论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='underwriting.insuranceapplication', verbose_name='投保申请')),
            ],
        ),
    ]
