# Generated by Django 5.2.15 on 2026-06-12 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0005_riskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='underwritingtask',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='underwriting.insuranceapplication', verbose_name='投保申请'),
        ),
        migrations.AddField(
            model_name='underwritingtask',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=50, verbose_name='核保人员'),
        ),
        migrations.AddField(
            model_name='underwritingtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='underwritingtask',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='underwriting.policy', verbose_name='保单'),
        ),
    ]
