# Generated by Django 5.2.15 on 2026-06-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0006_underwritingtask_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('decision', '提交结论'), ('create_policy', '生成保单'), ('update', '更新')], default='decision', max_length=30, verbose_name='操作类型'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='from_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='原状态'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='operator',
            field=models.CharField(blank=True, max_length=50, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='to_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='新状态'),
        ),
    ]
