# Generated by Django 5.2.15 on 2026-06-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0007_auditlog_action_auditlog_from_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy', to='underwriting.insuranceapplication', verbose_name='投保申请'),
        ),
    ]
