# Generated by Django 5.2.15 on 2026-06-17 03:14

import django.db.models.deletion
from django.db import migrations, models


def create_default_form_template(apps, schema_editor):
    FormTemplate = apps.get_model('underwriting', 'FormTemplate')
    FormFieldConfiguration = apps.get_model('underwriting', 'FormFieldConfiguration')

    template, _ = FormTemplate.objects.get_or_create(
        code='customer-intake',
        defaults={
            'name': '客户信息采集模板',
            'customer_type': 'all',
            'description': '按客户类型展示个人或企业客户需要填写的字段，可复制为其他业务模板复用。',
            'is_active': True,
        },
    )

    fields = [
        (10, 'customer_name', '客户名称', 'text', 'all', True, '', '个人姓名、企业简称或企业全称', ''),
        (20, 'phone', '手机号', 'text', 'personal', False, '', '个人客户联系方式', ''),
        (30, 'id_number', '身份证号', 'text', 'personal', False, '', '个人客户证件号码', ''),
        (40, 'company_name', '企业名称', 'text', 'company', True, '', '企业工商登记名称', ''),
        (50, 'unified_social_credit_code', '统一社会信用代码', 'text', 'company', False, '', '企业统一社会信用代码', ''),
        (60, 'contact_person', '联系人', 'text', 'company', False, '', '企业业务联系人', ''),
        (70, 'contact_phone', '联系电话', 'text', 'company', False, '', '企业联系人电话', ''),
        (80, 'registered_address', '注册地址', 'text', 'company', False, '', '企业注册地址', ''),
        (90, 'remark', '备注', 'textarea', 'all', False, '', '补充说明', ''),
    ]

    for sort_order, field_key, field_label, control_type, customer_type, is_required, default_value, help_text, option_values in fields:
        FormFieldConfiguration.objects.get_or_create(
            template=template,
            field_key=field_key,
            defaults={
                'sort_order': sort_order,
                'field_label': field_label,
                'control_type': control_type,
                'customer_type': customer_type,
                'is_required': is_required,
                'default_value': default_value,
                'help_text': help_text,
                'option_values': option_values,
                'is_enabled': True,
            },
        )


def remove_default_form_template(apps, schema_editor):
    FormTemplate = apps.get_model('underwriting', 'FormTemplate')
    FormTemplate.objects.filter(code='customer-intake').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0008_policy_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='模板名称')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='模板编码')),
                ('customer_type', models.CharField(choices=[('all', '全部客户'), ('personal', '个人客户'), ('company', '企业客户')], default='all', max_length=20, verbose_name='适用客户类型')),
                ('description', models.TextField(blank=True, verbose_name='模板说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '表单配置',
                'verbose_name_plural': '表单配置',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(max_length=80, verbose_name='字段标识')),
                ('field_label', models.CharField(max_length=80, verbose_name='字段名称')),
                ('control_type', models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('number', '数字'), ('select', '下拉选择'), ('date', '日期'), ('checkbox', '勾选框')], default='text', max_length=20, verbose_name='控件类型')),
                ('customer_type', models.CharField(choices=[('all', '全部客户'), ('personal', '个人客户'), ('company', '企业客户')], default='all', max_length=20, verbose_name='展示客户类型')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('default_value', models.CharField(blank=True, max_length=200, verbose_name='默认内容')),
                ('option_values', models.TextField(blank=True, help_text='下拉选择时每行一个选项', verbose_name='选项内容')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='填写提示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='underwriting.formtemplate', verbose_name='所属模板')),
            ],
            options={
                'verbose_name': '表单字段',
                'verbose_name_plural': '表单字段',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('template', 'field_key')},
            },
        ),
        migrations.RunPython(create_default_form_template, remove_default_form_template),
    ]
