# Generated by Django 5.2.15 on 2026-06-17 07:19

from django.db import migrations, models


def create_application_form_template(apps, schema_editor):
    FormTemplate = apps.get_model('underwriting', 'FormTemplate')
    FormFieldConfiguration = apps.get_model('underwriting', 'FormFieldConfiguration')

    template, _ = FormTemplate.objects.get_or_create(
        code='application-intake',
        defaults={
            'name': '投保申请采集模板',
            'form_type': 'application',
            'customer_type': 'all',
            'description': '控制新增/编辑投保申请页面展示的字段顺序、名称、控件类型和必填项。',
            'is_active': True,
        },
    )

    fields = [
        (10, 'customer', '投保客户', 'text', True, '', '搜索并选择已有客户'),
        (20, 'application_no', '投保申请号', 'text', True, '', '例如：APP20260617001'),
        (30, 'insurance_type', '险种类型', 'select', True, 'property', ''),
        (40, 'subject_name', '保险标的', 'text', True, '', '填写车辆、房屋、项目或货物名称'),
        (50, 'subject_address', '标的地址', 'text', False, '', '保险标的所在地'),
        (60, 'insured_amount', '保险金额', 'number', True, '', ''),
        (70, 'estimated_premium', '预估保费', 'number', True, '', ''),
        (80, 'status', '申请状态', 'select', True, 'submitted', ''),
        (90, 'remark', '备注', 'textarea', False, '', '补充说明'),
    ]

    for sort_order, field_key, field_label, control_type, is_required, default_value, help_text in fields:
        FormFieldConfiguration.objects.get_or_create(
            template=template,
            field_key=field_key,
            defaults={
                'sort_order': sort_order,
                'field_label': field_label,
                'control_type': control_type,
                'customer_type': 'all',
                'is_required': is_required,
                'default_value': default_value,
                'help_text': help_text,
                'option_values': '',
                'is_enabled': True,
            },
        )


def remove_application_form_template(apps, schema_editor):
    FormTemplate = apps.get_model('underwriting', 'FormTemplate')
    FormTemplate.objects.filter(code='application-intake').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0009_formtemplate_formfieldconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='form_type',
            field=models.CharField(choices=[('customer', '客户管理表单'), ('application', '投保申请表单')], default='customer', max_length=30, verbose_name='配置页面'),
        ),
        migrations.RunPython(create_application_form_template, remove_application_form_template),
    ]
