# Generated by Django 5.2.15 on 2026-06-17 08:14

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def populate_customer_no(apps, schema_editor):
    Customer = apps.get_model('underwriting', 'Customer')
    for index, customer in enumerate(Customer.objects.order_by('id'), start=1):
        if not customer.customer_no:
            customer.customer_no = f"C{index:06d}"
            customer.save(update_fields=['customer_no'])


def seed_security_data(apps, schema_editor):
    Company = apps.get_model('underwriting', 'Company')
    Department = apps.get_model('underwriting', 'Department')
    PermissionPoint = apps.get_model('underwriting', 'PermissionPoint')
    SystemRole = apps.get_model('underwriting', 'SystemRole')
    UserProfile = apps.get_model('underwriting', 'UserProfile')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    company, _ = Company.objects.get_or_create(
        code='HQ',
        defaults={'name': '总公司', 'is_active': True, 'remark': '系统默认公司'},
    )
    department, _ = Department.objects.get_or_create(
        company=company,
        code='ADMIN',
        defaults={'name': '系统管理部', 'is_active': True, 'remark': '系统默认部门'},
    )

    permission_items = [
        ('工作台', 'dashboard.view', '查看工作台'),
        ('客户管理', 'customer.create', '新增客户'),
        ('客户管理', 'customer.edit', '编辑客户'),
        ('客户管理', 'customer.delete', '删除客户'),
        ('投保申请', 'application.create', '新增投保申请'),
        ('投保申请', 'application.edit', '编辑投保申请'),
        ('投保申请', 'application.delete', '删除投保申请'),
        ('风险评估', 'risk.edit', '编辑风险评估'),
        ('核保任务', 'underwriting.create', '新增核保任务'),
        ('核保任务', 'underwriting.edit', '编辑核保任务'),
        ('核保任务', 'underwriting.decision', '提交核保结论'),
        ('核保任务', 'underwriting.delete', '删除核保任务'),
        ('保单管理', 'policy.edit', '编辑保单'),
        ('保单管理', 'policy.delete', '删除保单'),
        ('系统后台', 'system.form_config', '表单配置'),
        ('系统后台', 'system.user', '用户管理'),
        ('系统后台', 'system.role', '角色权限'),
        ('系统后台', 'system.company', '公司管理'),
        ('系统后台', 'system.department', '部门管理'),
        ('系统后台', 'system.operation_log', '操作日志'),
        ('系统后台', 'system.db_check', '系统检测'),
    ]

    for sort_order, item in enumerate(permission_items, start=1):
        module, code, name = item
        PermissionPoint.objects.get_or_create(
            code=code,
            defaults={'module': module, 'name': name, 'sort_order': sort_order},
        )

    role, _ = SystemRole.objects.get_or_create(
        code='admin',
        defaults={'name': '系统管理员', 'is_active': True, 'remark': '拥有全部权限'},
    )
    role.permissions.set(PermissionPoint.objects.all())

    user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'first_name': '系统管理员',
            'is_staff': True,
            'is_superuser': True,
            'is_active': True,
            'password': make_password('Admin@123456'),
        },
    )
    profile, _ = UserProfile.objects.get_or_create(
        user=user,
        defaults={'company': company, 'department': department, 'remark': '系统默认管理员'},
    )
    if not profile.company:
        profile.company = company
    if not profile.department:
        profile.department = department
    profile.save()
    profile.roles.add(role)


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0010_formtemplate_form_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='公司编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '权限点',
                'verbose_name_plural': '权限点',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='客户ID'),
        ),
        migrations.RunPython(populate_customer_no, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='客户ID'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, verbose_name='部门编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='underwriting.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['company__name', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='账号快照')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='公司快照')),
                ('department_name', models.CharField(blank=True, max_length=100, verbose_name='部门快照')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('target_type', models.CharField(blank=True, max_length=80, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=80, verbose_name='对象ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='操作说明')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='请求路径')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='角色名称')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='角色编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='underwriting.permissionpoint', verbose_name='权限点')),
            ],
            options={
                'verbose_name': '系统角色',
                'verbose_name_plural': '系统角色',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='underwriting.company', verbose_name='所属公司')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='underwriting.department', verbose_name='所属部门')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='underwriting.systemrole', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='登录账号')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.RunPython(seed_security_data, migrations.RunPython.noop),
    ]
